// tutorials/spring-security-modules/spring-security-oauth2-bff/angular-ui/src/app/about.view.ts
import { Component } from '@angular/core';
import { NavigationComponent } from './navigation.component';

@Component({
  selector: 'app-about',
  standalone: true,
  imports: [NavigationComponent],
  template: `<app-navigation
      [destination]="['']"
      label="HOME"
    ></app-navigation>
    <p>
      This application is a show-case for an Angular app consuming a REST API
      through an OAuth2 BFF.
    </p>`,
  styles: ``,
})
export class AboutView {}

// tutorials/spring-security-modules/spring-security-oauth2-bff/vue-ui/src/views/AboutView.vue
<template>
  <div class="about">
    <p>This application is a show-case for an Angular app consuming a REST API
      through an OAuth2 BFF.</p>
  </div>
</template>

<style>
@media (min-width: 1024px) {
  .about {
    min-height: 100vh;
    display: flex;
    align-items: center;
  }
}
</style>
