// tutorials/spring-security-modules/spring-security-oauth2-bff/angular-ui/src/app/home.view.ts
import { Component } from '@angular/core';
import { Subscription } from 'rxjs';
import { NavigationComponent } from './navigation.component';
import { User, UserService } from './auth/user.service';

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [NavigationComponent],
  template: `<app-navigation
      [destination]="['about']"
      label="About"
    ></app-navigation>
    <p>{{ message }}</p>`,
  styles: [],
})
export class HomeView {
  message = '';

  private userSubscription?: Subscription;

  constructor(user: UserService) {
    this.userSubscription = user.valueChanges.subscribe((u) => {
      this.message = u.isAuthenticated
        ? `Hi ${u.name}, you are granted with ${HomeView.rolesStr(u)}.`
        : 'You are not authenticated.';
    });
  }

  static rolesStr(user: User) {
    if(!user?.roles?.length) {
      return '[]'
    }
    return `["${user.roles.join('", "')}"]`
  }

  ngOnDestroy() {
    this.userSubscription?.unsubscribe();
  }
}

// tutorials/spring-security-modules/spring-security-oauth2-bff/vue-ui/src/views/HomeView.vue
<script setup lang="ts">
import { inject } from 'vue';
import { User, UserService } from '../user.service'

// inject the singleton defined in main.js
const user = inject('UserService') as UserService;
function message(user: User) {
  return user.isAuthenticated 
  ? `Hi ${user.name}, you are granted with ${rolesStr(user)}.`
  : 'You are not authenticated.'
}

function rolesStr(user: User) {
  if(!user?.roles?.length) {
    return '[]'
  }
  return `["${user.roles.join('", "')}"]`
}
</script>

<template>
  <main>
    <p>{{ message(user.current.value) }}</p>
  </main>
</template>
